export const initialEditProfileFields = [
  {
    type: "text",
    name: "phoneNumber",
    label: "Phone Number",
    placeholder: "phone Number",
    isRequired: true,
    defaultValue: "",
    isReadOnly: false,
    isHidden: false,
  },
  {
    type: "text",
    name: "job",
    label: "Job",
    placeholder: "placeholder",
    isRequired: true,
    defaultValue: "",
    isReadOnly: false,
    isHidden: false,
  },
  {
    type: "text",
    name: "firstName",
    label: "First Name",
    placeholder: "placeholder",
    isRequired: true,
    defaultValue: "",
    isReadOnly: false,
    isHidden: false,
  },
  {
    type: "text",
    name: "lastName",
    label: "Last Name",
    placeholder: "placeholder",
    isRequired: true,
    defaultValue: "",
    isReadOnly: false,
    isHidden: false,
  },
  {
    type: "text",
    name: "cin",
    label: "CIN",
    placeholder: "placeholder",
    isRequired: true,
    defaultValue: "",
    isReadOnly: false,
    isHidden: false,
  },
  {
    type: "select",
    name: "gender",
    label: "Gender",
    isRequired: true,
    options: [
      { value: "male", label: "male" },
      { value: "female", label: "female" },
    ],
  },
  {
    type: "select",
    name: "governorate",
    label: "Governorate",
    isRequired: true,

    options: [
      { value: "option1", label: "option1" },
      { value: "option2", label: "option2" },
      { value: "option3", label: "option3" },
    ],
  },
  {
    type: "select",
    name: "municipality",
    label: "Municipality",
    isRequired: true,
    options: [{ value: "option1", label: "" }],
  },
];
