export const fieldsInitialState = [
  {
    type: "text",
    name: "phoneNumber",
    label: "Phone Number",
    placeholder: "phone Number",
    required: true,
    defaultValue: "555555",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "job",
    label: "Job",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "firstName",
    label: "First Name",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "file",
    name: "lastName",
    label: "Last Name",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "cin",
    label: "CIN",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "select",
    name: "gender",
    label: "Gender",
    required: true,
    options: [
      { value: "option1", label: "option1" },
      { value: "option2", label: "option2" },
      { value: "option3", label: "option3" },
    ],
  },
];

export const fieldsWithOrderChanged = [
  {
    type: "text",
    name: "job",
    label: "Job",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "file",
    name: "lastName",
    label: "Last Name",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "select",
    name: "gender",
    label: "Gender",
    required: true,
    options: [
      { value: "option1", label: "option1" },
      { value: "option2", label: "option2" },
      { value: "option3", label: "option3" },
    ],
  },
  {
    type: "text",
    name: "firstName",
    label: "First Name",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "phoneNumber",
    label: "Phone Number",
    placeholder: "phone Number",
    required: true,
    defaultValue: "555555",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "cin",
    label: "CIN",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
];
export const fieldsWidthNoneObject = [
  {
    type: "text",
    name: "phoneNumber",
    label: "Phone Number",
    placeholder: "phone Number",
    required: true,
    defaultValue: "555555",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "job",
    label: "Job",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "firstName",
    label: "First Name",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "file",
    name: "lastName",
    label: "Last Name",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "cin",
    label: "CIN",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "select",
    name: "gender",
    label: "Gender",
    required: true,
    options: [
      { value: "option1", label: "option1" },
      { value: "option2", label: "option2" },
      { value: "option3", label: "option3" },
    ],
  },
  {
    type: "none",
    name: "none",
  },
];

export const fieldsContainArrayOfFields = [
  {
    type: "text",
    name: "phoneNumber",
    label: "Phone Number",
    placeholder: "phone Number",
    required: true,
    defaultValue: "555555",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "job",
    label: "Job",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  [
    {
      type: "text",
      name: "firstName",
      label: "First Name",
      placeholder: "placeholder",
      required: true,
      defaultValue: "",
      readOnly: false,
      hidden: false,
    },
    {
      type: "file",
      name: "lastName",
      label: "Last Name",
      placeholder: "placeholder",
      required: true,
      defaultValue: "",
      readOnly: false,
      hidden: false,
    },
  ],
  {
    type: "text",
    name: "cin",
    label: "CIN",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "select",
    name: "gender",
    label: "Gender",
    required: true,
    options: [
      { value: "option1", label: "option1" },
      { value: "option2", label: "option2" },
      { value: "option3", label: "option3" },
    ],
  },
];

export const fieldsContainNoneObjectInsideTheInnerArray = [
  {
    type: "text",
    name: "phoneNumber",
    label: "Phone Number",
    placeholder: "phone Number",
    required: true,
    defaultValue: "555555",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "job",
    label: "Job",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  [
    {
      type: "text",
      name: "firstName",
      label: "First Name",
      placeholder: "placeholder",
      required: true,
      defaultValue: "",
      readOnly: false,
      hidden: false,
    },
    {
      type: "none",
      name: "none",
    },
  ],
  {
    type: "file",
    name: "lastName",
    label: "Last Name",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },

  {
    type: "text",
    name: "cin",
    label: "CIN",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "select",
    name: "gender",
    label: "Gender",
    required: true,
    options: [
      { value: "option1", label: "option1" },
      { value: "option2", label: "option2" },
      { value: "option3", label: "option3" },
    ],
  },
];
