export const defaultProps = {
  type: "datePicker",
  label: "Date Picker",
  required: false,
  defaultValue: "",
  readOnly: false,
  hidden: false,
  multiple: true,
  error: "default error message",
  touched: false,
  withRequiredStar: true,
  locale: "en",
  dateFormat: "MM/DD/YYYY",
  isAmPm: false,
};
