export const updateDefaultValuesActionResult = [
  {
    type: "text",
    name: "phoneNumber",
    label: "Phone Number",
    placeholder: "phone Number",
    required: true,
    defaultValue: "28012516",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "job",
    label: "Job",
    placeholder: "placeholder",
    required: true,
    defaultValue: "",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "firstName",
    label: "First Name",
    placeholder: "placeholder",
    required: true,
    defaultValue: "mohamed",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "lastName",
    label: "Last Name",
    placeholder: "placeholder",
    required: true,
    defaultValue: "jrad",
    readOnly: false,
    hidden: false,
  },
  {
    type: "text",
    name: "cin",
    label: "CIN",
    placeholder: "placeholder",
    defaultValue: "99999999",
    required: true,
    readOnly: false,
    hidden: false,
  },
  {
    type: "select",
    name: "gender",
    label: "Gender",
    required: true,
    defaultValue: "male",
    options: [
      { value: "male", label: "male" },
      { value: "female", label: "female" },
    ],
  },
  {
    type: "birthDate",
    name: "birthDate",
    label: " Birth Date",
    readOnly: false,
    hidden: false,
    required: true,
    defaultValue: "1998-04-23T18:25:43.511Z",
  },
  {
    type: "select",
    name: "governorate",
    label: "Governorate",
    required: true,
    defaultValue: "medenine",
    options: [
      { value: "option1", label: "option1" },
      { value: "option2", label: "option2" },
      { value: "option3", label: "option3" },
    ],
  },
  {
    type: "select",
    name: "municipality",
    label: "Municipality",
    required: true,
    hidden: false,
    defaultValue: "djerba",
    options: [{ value: "option1", label: "" }],
  },
  {
    type: "text",
    name: "address",
    label: "Address",
    required: true,
    defaultValue: "sousse",
    options: [
      { value: "option1", label: "option1" },
      { value: "option2", label: "option2" },
      { value: "option3", label: "option3" },
    ],
  },
];
